name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Jekyll dependencies
        run: bundle install --path vendor/bundle
      - name: Validate JSON syntax
        uses: limitusus/json-syntax-check@v2.0.2
        with:
          pattern: '\\bio.json$'
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
